### ISSUE TITLE
Polygon outline not supported

### ISSUE THREAD

**Issue by davidmanzanares** [CartoDB/tangram-reference#10]
Tangram doesn't support, at this moment, rendering polygons with outlines.

The current behavior in Builder-embed right now is to ignore it. We should fallback to raster in those cases.

**Comment by davidmanzanares** [comment]
Actually, it's not that clear that it doesn't support it. Wait for https://github.com/tangrams/tangram/issues/585

**Comment by davidmanzanares** [comment]
Following https://github.com/tangrams/tangram/issues/585 , polygon outline is semi-supported, a trick is needed, and even with the trick, draw order and blending is broken, and they don't have plans to fix it. In fact, it seems that it will conflict with their 3D rendering, therefore, a PR from my part would probably be denied.

We need to decide when we want to fallback to raster, but the difference between the correct Mapnik render and the wrong Tangram render depends on many things.

**Comment by davidmanzanares** [comment]
Small clarification. CartoCSS doesn't support as is polygon outlines, but you can activate multiple symbolizers on the same layer to do exactly that. The multiple symbolizers on one layer behavior is the unsupported one.

**Comment by rochoa** [comment]
No further development is happening in this project.
